

resource:
  imageServer: http://localhost:8080/image.dev.com
  emailServer: http://localhost:8080/email.dev.com

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: abc
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#spring:
  #​   thymeleaf:
  #      cache: false
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl